require('./config.js')
const { connect } = require('./infra/db/mongo.js')
const { GetUserProvider } = require('./infra/services/user.js')
const { EventService } = require('./infra/services/events.js')
const { info } = require('./infra/support/log.js')
const http = require('./http/index.js')
const socket = require('./socket/index.js')
connect().then(async db => {
  const userProvider = GetUserProvider()
  const eventS = new EventService()
  const app = await http(db, eventS, userProvider)
  await socket(app.server, db, userProvider)
  info(`Socket attached with http server.`)
})